name: hyp3-insar-gamma
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  # For packaging, and testing
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - setuptools
  - setuptools_scm
  - wheel
  # For running
  - hyp3lib>=1.6.1,<2
  - importlib_metadata
  - lxml
  - pip:
    # for packaging and testing
    - s3pypi
    - safety
